// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh9iP_te_zeDx2Kjoa7h5RvQZMlg0wYy8',
    appId: '1:138260154259:web:936ade1ed2e5d3dcfc8a66',
    messagingSenderId: '138260154259',
    projectId: 'a-eye-26956',
    authDomain: 'a-eye-26956.firebaseapp.com',
    storageBucket: 'a-eye-26956.firebasestorage.app',
    measurementId: 'G-NDRB1XLYJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0BUPvpMnIVoZnzxeVzq7JpeCls33hbJo',
    appId: '1:138260154259:android:353f6ae808fa0ac0fc8a66',
    messagingSenderId: '138260154259',
    projectId: 'a-eye-26956',
    storageBucket: 'a-eye-26956.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMcNTSx3naTMuoQlScwfolpcCf6ZlX0kc',
    appId: '1:138260154259:ios:0f7506ee06a96e68fc8a66',
    messagingSenderId: '138260154259',
    projectId: 'a-eye-26956',
    storageBucket: 'a-eye-26956.firebasestorage.app',
    iosBundleId: 'com.example.aEye',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMcNTSx3naTMuoQlScwfolpcCf6ZlX0kc',
    appId: '1:138260154259:ios:0f7506ee06a96e68fc8a66',
    messagingSenderId: '138260154259',
    projectId: 'a-eye-26956',
    storageBucket: 'a-eye-26956.firebasestorage.app',
    iosBundleId: 'com.example.aEye',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh9iP_te_zeDx2Kjoa7h5RvQZMlg0wYy8',
    appId: '1:138260154259:web:10b69167e5e1c63cfc8a66',
    messagingSenderId: '138260154259',
    projectId: 'a-eye-26956',
    authDomain: 'a-eye-26956.firebaseapp.com',
    storageBucket: 'a-eye-26956.firebasestorage.app',
    measurementId: 'G-F3GDJJLGJM',
  );
}
