/*
 * Program Title: firebase_options.dart
 *
 * Programmers:
 *   Albonia, Jade Lorenz
 *   Villegas, Jedidiah
 *   Velante, Kamilah Kaye
 *   Rivera, Rei Djemf M.
 *
 * Where the program fits in the general system design:
 *   This module is the Configuration Layer for the Firebase SDK. It is
 *   automatically generated by the FlutterFire CLI but is integral to the
 *   application's startup. It serves as the "Bridge" between the Flutter
 *   client code and the Google Cloud backend. It provides the specific
 *   API Keys, App IDs, and Project Identifiers required to authenticate
 *   the app with Firebase services (Auth, Firestore, Storage) depending
 *   on which platform (Android, iOS, Web) the app is currently running on.
 *
 * Date Written: October 2025
 * Date Revised: November 2025
 *
 * Purpose:
 *   To encapsulate platform-specific configuration data in a single static
 *   class, allowing `Firebase.initializeApp()` to run dynamically without
 *   hardcoding checks in the main entry point.
 *
 * Data Structures, Algorithms, and Control:
 *
 *   Data Structures:
 *     * FirebaseOptions: A configuration object containing API keys and IDs.
 *
 *   Algorithms:
 *     * Platform Detection: Uses `defaultTargetPlatform` and `kIsWeb` to
 *       determine the runtime environment (e.g., is this an iPhone or a Browser?).
 *
 *   Control:
 *     * Switch Case: Routes the initialization logic to return the correct
 *       configuration set (e.g., `android` vs `ios`) or throws an error if
 *       the platform is unsupported (e.g., Linux).
 */


// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  // -- ALGORITHM: PLATFORM DETECTION --
  // Dynamically returns the correct config object based on the OS.
  static FirebaseOptions get currentPlatform {
    // Priority Check: Web is a special case in Flutter (can run on any OS)
    if (kIsWeb) {
      return web;
    }
    // -- CONTROL: OS BRANCHING --
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
      // Error Handling: Explicitly fail on unsupported platforms
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // -- CONFIGURATION: WEB --
  // Credentials for the browser-based version of the app
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh9iP_te_zeDx2Kjoa7h5RvQZMlg0wYy8',
    appId: '1:138260154259:web:936ade1ed2e5d3dcfc8a66',
    messagingSenderId: '138260154259',
    projectId: 'a-eye-26956',
    authDomain: 'a-eye-26956.firebaseapp.com',
    storageBucket: 'a-eye-26956.firebasestorage.app',
    measurementId: 'G-NDRB1XLYJ4',
  );

  // -- CONFIGURATION: ANDROID --
  // Credentials for the native Android application
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0BUPvpMnIVoZnzxeVzq7JpeCls33hbJo',
    appId: '1:138260154259:android:353f6ae808fa0ac0fc8a66',
    messagingSenderId: '138260154259',
    projectId: 'a-eye-26956',
    storageBucket: 'a-eye-26956.firebasestorage.app',
  );

  // -- CONFIGURATION: iOS --
  // Credentials for the native iPhone/iPad application
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMcNTSx3naTMuoQlScwfolpcCf6ZlX0kc',
    appId: '1:138260154259:ios:0f7506ee06a96e68fc8a66',
    messagingSenderId: '138260154259',
    projectId: 'a-eye-26956',
    storageBucket: 'a-eye-26956.firebasestorage.app',
    iosBundleId: 'com.example.aEye',
  );

  // -- CONFIGURATION: MACOS --
  // Credentials for the desktop Mac application
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMcNTSx3naTMuoQlScwfolpcCf6ZlX0kc',
    appId: '1:138260154259:ios:0f7506ee06a96e68fc8a66',
    messagingSenderId: '138260154259',
    projectId: 'a-eye-26956',
    storageBucket: 'a-eye-26956.firebasestorage.app',
    iosBundleId: 'com.example.aEye',
  );

  // -- CONFIGURATION: WINDOWS --
  // Credentials for the desktop Windows application
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh9iP_te_zeDx2Kjoa7h5RvQZMlg0wYy8',
    appId: '1:138260154259:web:10b69167e5e1c63cfc8a66',
    messagingSenderId: '138260154259',
    projectId: 'a-eye-26956',
    authDomain: 'a-eye-26956.firebaseapp.com',
    storageBucket: 'a-eye-26956.firebasestorage.app',
    measurementId: 'G-F3GDJJLGJM',
  );

}